# Generated by Django 5.2.11 on 2026-02-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0002_alter_session_name'),
        ('notifications', '0002_notification_delete_processstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ngenerate_sessions.session'),
        ),
    ]
