# Generated by Django 5.2.11 on 2026-03-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['session', 'task_type'], name='notificatio_session_10bc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['generation_run'], name='notificatio_generat_294dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'analysis')), fields=('session', 'task_type'), name='unique_session_analysis_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'generation')), fields=('generation_run',), name='unique_generation_run_notification'),
        ),
    ]
