# Generated by Django 5.2.11 on 2026-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
