# Generated by Django 5.2.11 on 2026-03-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0008_alter_processingstep_options_and_more'),
        ('notifications', '0004_notification_file_path'),
        ('novels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_session_task_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['generation_run'], name='notificatio_generat_294dbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'analysis')), fields=('session', 'task_type'), name='unique_session_analysis_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'generation')), fields=('generation_run',), name='unique_generation_run_notification'),
        ),
    ]
