# Generated by Django 5.2.11 on 2026-03-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_unique_session_task_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task_type',
            field=models.CharField(blank=True, choices=[('analysis', 'Analysis'), ('generation', 'Generation'), ('upload', 'Upload'), ('fix_text', 'Fix Text')], max_length=20, null=True),
        ),
    ]
