# Generated by Django 5.2.11 on 2026-03-06 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngenerate_sessions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('credits_limit', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30)])),
                ('duration_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('recommendation', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.JSONField(default=list, help_text='เก็บรายการสิทธิประโยชน์เป็น list ของ string')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'PENDING'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Topup'), ('analysis_lock', 'Analysis Lock'), ('analysis_complete', 'Analysis Complete'), ('generation_lock', 'Generation Lock'), ('generation_complete', 'Generation Complete'), ('refund', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to='ngenerate_sessions.session')),
            ],
        ),
    ]
