# Generated by Django 5.2.11 on 2026-03-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.package'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to='payments.transaction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'pending')), fields=('user',), name='unique_pending_transaction_per_user'),
        ),
        migrations.AddIndex(
            model_name='creditlog',
            index=models.Index(fields=['user', '-created_at'], name='payments_cr_user_id_756e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlog',
            index=models.Index(fields=['session'], name='payments_cr_session_5d9823_idx'),
        ),
    ]
