# Generated by Django 5.2.11 on 2026-02-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to='sessions.session'),
        ),
    ]
