# Generated by Django 5.2.11 on 2026-02-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0002_alter_session_name'),
        ('payments', '0002_creditlog_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to='ngenerate_sessions.session'),
        ),
    ]
