# Generated by Django 5.2.11 on 2026-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
