# Generated by Django 5.2.11 on 2026-03-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_idempotency_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='omise_charge_id',
            new_name='stripe_session_id',
        ),
    ]
