# Generated by Django 5.2.11 on 2026-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='omise_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
