# Generated by Django 5.2.11 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_creditlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.JSONField(default=list, help_text='เก็บรายการสิทธิประโยชน์เป็น list ของ string'),
        ),
        migrations.AddField(
            model_name='package',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
