# Generated by Django 5.2.11 on 2026-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_omise_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlog',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
