# Generated by Django 5.2.11 on 2026-02-27 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_package_features_package_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'success')), fields=('user',), name='unique_active_success_transaction_per_user'),
        ),
    ]
