# Generated by Django 5.2.11 on 2026-02-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('appearance', models.TextField(blank=True)),
                ('outfit', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('base_personality', models.TextField(blank=True)),
                ('master_image_path', models.FileField(blank=True, null=True, upload_to='')),
                ('master_voice_path', models.FileField(blank=True, null=True, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='novels.novel')),
            ],
            options={
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('session_type', models.CharField(choices=[('analysis', 'Analysis Only'), ('full', 'Analysis + Generation')], default='analysis', max_length=20)),
                ('analyze_credits', models.PositiveIntegerField(default=0)),
                ('generate_credits', models.PositiveIntegerField(default=0)),
                ('locked_credits', models.PositiveIntegerField(default=0)),
                ('is_analysis_done', models.BooleanField(default=False)),
                ('is_generation_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_finished_at', models.DateTimeField(blank=True, null=True)),
                ('generation_finished_at', models.DateTimeField(blank=True, null=True)),
                ('chapters', models.ManyToManyField(related_name='sessions', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='novels.novel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('analysis', 'Analysis'), ('generation', 'Generation')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='ngenerate_sessions.session')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.PositiveIntegerField()),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('narration', 'Narration'), ('dialogue', 'Dialogue')], default='narration', max_length=20)),
                ('emotion', models.CharField(blank=True, max_length=50)),
                ('sentence', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter')),
                ('character_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='ngenerate_sessions.characterprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='ngenerate_sessions.session')),
            ],
            options={
                'unique_together': {('session', 'chapter', 'sentence_index')},
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='ngenerate_sessions.session')),
            ],
            options={
                'unique_together': {('session', 'chapter')},
            },
        ),
    ]
