# Generated by Django 5.2.11 on 2026-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appearance', models.TextField(blank=True)),
                ('appearance_tags', models.TextField(blank=True)),
                ('outfit', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('base_personality', models.TextField(blank=True)),
                ('aliases', models.TextField(blank=True, default='')),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('style', models.CharField(choices=[('ghibli', 'Ghibli'), ('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], max_length=50)),
                ('narrator_voice', models.CharField(choices=[('man1', 'Man 1'), ('man2', 'Man 2'), ('girl1', 'Girl 1')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generate_credits', models.PositiveIntegerField(default=0)),
                ('locked_credits', models.PositiveIntegerField(default=0)),
                ('generation_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_index', models.PositiveIntegerField(default=1)),
                ('sentence_start', models.PositiveIntegerField(blank=True, null=True)),
                ('sentence_end', models.PositiveIntegerField(blank=True, null=True)),
                ('scene_description', models.TextField(blank=True)),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('analysis', 'Analysis')], default='analysis', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SceneCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(blank=True, max_length=200)),
                ('expression', models.CharField(blank=True, max_length=100)),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.PositiveIntegerField()),
                ('tts_text', models.TextField(blank=True)),
                ('sentence', models.TextField()),
            ],
            options={
                'ordering': ['session_id', 'chapter_id', 'sentence_index'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('session_type', models.CharField(choices=[('analysis', 'Analysis Only'), ('full', 'Analysis + Generation')], default='analysis', max_length=50)),
                ('current_phase', models.CharField(choices=[('analysis', 'analysis'), ('generation', 'generation'), ('none', 'none')], default='none', max_length=20)),
                ('style', models.CharField(choices=[('ghibli', 'Ghibli'), ('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], default='ghibli', max_length=50)),
                ('narrator_voice', models.CharField(choices=[('man1', 'Man 1'), ('man2', 'Man 2'), ('girl1', 'Girl 1')], default='man1', max_length=20)),
                ('analyze_credits', models.PositiveIntegerField(default=0)),
                ('locked_credits', models.PositiveIntegerField(default=0)),
                ('is_analysis_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
