# Generated by Django 5.2.11 on 2026-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appearance', models.TextField(blank=True)),
                ('outfit', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('base_personality', models.TextField(blank=True)),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('analysis', 'Analysis'), ('generation', 'Generation')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.PositiveIntegerField()),
                ('sentence', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['session_id', 'chapter_id', 'sentence_index'],
            },
        ),
        migrations.CreateModel(
            name='SentenceCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('session_type', models.CharField(choices=[('analysis', 'Analysis Only'), ('full', 'Analysis + Generation')], default='analysis', max_length=50)),
                ('style', models.CharField(choices=[('chinese', 'Chinese'), ('japanese', 'Japanese'), ('futuristic', 'Futuristic'), ('medieval', 'Medieval'), ('ghibli', 'Ghibli')], default='ghibli', max_length=50)),
                ('analyze_credits', models.PositiveIntegerField(default=0)),
                ('generate_credits', models.PositiveIntegerField(default=0)),
                ('locked_credits', models.PositiveIntegerField(default=0)),
                ('is_analysis_done', models.BooleanField(default=False)),
                ('is_generation_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('narrator_voice', models.CharField(choices=[('man1', 'Man 1'), ('man2', 'Man 2'), ('girl1', 'Girl 1')], default='man1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_finished_at', models.DateTimeField(blank=True, null=True)),
                ('generation_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
