# Generated by Django 5.2.11 on 2026-03-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngenerate_sessions', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='generationprocessingstep',
            name='generation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='scenecharacter',
            name='character_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='ngenerate_sessions.characterprofile'),
        ),
        migrations.AddField(
            model_name='scenecharacter',
            name='illustration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='ngenerate_sessions.illustration'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='session',
            name='chapters',
            field=models.ManyToManyField(related_name='sessions', to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='session',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='scenecharacter',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='processingstep',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='ngenerate_sessions.session'),
        ),
        migrations.AddIndex(
            model_name='characterprofile',
            index=models.Index(fields=['novel'], name='ngenerate_s_novel_i_f8a096_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='characterprofile',
            unique_together={('novel', 'name')},
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['session', 'sentence_index'], name='ngenerate_s_session_62449c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('session', 'chapter', 'sentence_index')},
        ),
        migrations.AddIndex(
            model_name='scenecharacter',
            index=models.Index(fields=['session'], name='ngenerate_s_session_9b167a_idx'),
        ),
        migrations.AddIndex(
            model_name='scenecharacter',
            index=models.Index(fields=['illustration'], name='ngenerate_s_illustr_fc9fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenecharacter',
            unique_together={('illustration', 'character_profile')},
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['session'], name='ngenerate_s_session_c94696_idx'),
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['session', 'chapter'], name='ngenerate_s_session_0e25ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='illustration',
            unique_together={('session', 'chapter', 'scene_index')},
        ),
        migrations.AddConstraint(
            model_name='generationrun',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_generation_run_version_per_session'),
        ),
    ]
