# Generated by Django 5.2.11 on 2026-03-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngenerate_sessions', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ngenerate_sessions.characterprofile'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='sentencecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_characters', to='ngenerate_sessions.character'),
        ),
        migrations.AddField(
            model_name='sentencecharacter',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_characters', to='ngenerate_sessions.sentence'),
        ),
        migrations.AddField(
            model_name='session',
            name='chapters',
            field=models.ManyToManyField(related_name='sessions', to='novels.chapter'),
        ),
        migrations.AddField(
            model_name='session',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='processingstep',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='character',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ngenerate_sessions.session'),
        ),
        migrations.AddIndex(
            model_name='characterprofile',
            index=models.Index(fields=['novel'], name='ngenerate_s_novel_i_f8a096_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='characterprofile',
            unique_together={('novel', 'name')},
        ),
        migrations.AddIndex(
            model_name='sentencecharacter',
            index=models.Index(fields=['sentence'], name='ngenerate_s_sentenc_59c0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sentencecharacter',
            index=models.Index(fields=['character'], name='ngenerate_s_charact_808633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentencecharacter',
            unique_together={('sentence', 'character')},
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['session', 'sentence_index'], name='ngenerate_s_session_62449c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('session', 'chapter', 'sentence_index')},
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['session'], name='ngenerate_s_session_c94696_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='illustration',
            unique_together={('session', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('session', 'chapter', 'character_profile', 'emotion')},
        ),
    ]
