# Generated by Django 5.2.11 on 2026-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_phase',
            field=models.CharField(choices=[('analysis', 'analysis'), ('generation', 'generation'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
