# Generated by Django 5.2.11 on 2026-02-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0002_alter_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='character_profile',
        ),
        migrations.AddField(
            model_name='session',
            name='style',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('japanese', 'Japanese'), ('futuristic', 'Futuristic'), ('medieval', 'Medieval'), ('ghibli', 'Ghibli')], default='ghibli', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('analysis', 'Analysis Only'), ('full', 'Analysis + Generation')], default='analysis', max_length=50),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('positive_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('image_path', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ngenerate_sessions.characterprofile')),
            ],
            options={
                'unique_together': {('profile', 'emotion')},
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='ngenerate_sessions.character'),
        ),
    ]
