# Generated by Django 5.2.11 on 2026-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='narrator_voice',
            field=models.CharField(choices=[('man1', 'Man 1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='style',
            field=models.CharField(choices=[('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='narrator_voice',
            field=models.CharField(choices=[('man1', 'Man 1')], default='man1', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='style',
            field=models.CharField(choices=[('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], default='ghibli', max_length=50),
        ),
    ]
