# Generated by Django 5.2.11 on 2026-02-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0003_remove_sentence_character_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_path',
        ),
    ]
