# Generated by Django 5.2.11 on 2026-03-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngenerate_sessions", "0003_session_current_phase"),
        ("novels", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="illustration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="illustration",
            name="scene_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="illustration",
            name="scene_index",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="illustration",
            name="sentence_end",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="illustration",
            name="sentence_start",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="illustration",
            unique_together={("session", "chapter", "scene_index")},
        ),
        migrations.AddIndex(
            model_name="illustration",
            index=models.Index(
                fields=["session", "chapter"], name="ngenerate_s_session_0e25ec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="character",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="character",
            name="chapter",
        ),
        migrations.AddField(
            model_name="character",
            name="illustration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="ngenerate_sessions.illustration",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="character",
            unique_together={
                ("session", "illustration", "character_profile", "emotion")
            },
        ),
        migrations.AddField(
            model_name="characterprofile",
            name="appearance_tags",
            field=models.TextField(blank=True),
        ),
    ]
