# Generated by Django 5.2.11 on 2026-02-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0004_remove_character_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='session',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ngenerate_sessions.session'),
            preserve_default=False,
        ),
    ]
