# Generated by Django 5.2.11 on 2026-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0004_alter_illustration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='tts_text',
            field=models.TextField(blank=True),
        ),
    ]
