# Generated by Django 5.2.11 on 2026-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0005_sentence_tts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
    ]
