# Generated by Django 5.2.11 on 2026-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0006_characterprofile_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='style',
            field=models.CharField(choices=[('ghibli', 'Ghibli'), ('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], default='ghibli', max_length=50),
        ),
    ]
