# Generated by Django 5.2.11 on 2026-03-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0007_alter_session_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingstep',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='generate_credits',
        ),
        migrations.RemoveField(
            model_name='session',
            name='generation_finished_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_generation_done',
        ),
        migrations.AlterField(
            model_name='processingstep',
            name='phase',
            field=models.CharField(choices=[('analysis', 'Analysis')], default='analysis', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('style', models.CharField(choices=[('ghibli', 'Ghibli'), ('chinese', 'Chinese Oil Painting'), ('chinese-modern', 'Chinese Modern (Xianxia)'), ('fantasy', 'Fantasy'), ('medieval', 'Medieval'), ('futuristic', 'Futuristic')], max_length=50)),
                ('narrator_voice', models.CharField(choices=[('man1', 'Man 1'), ('man2', 'Man 2'), ('girl1', 'Girl 1')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generate_credits', models.PositiveIntegerField(default=0)),
                ('locked_credits', models.PositiveIntegerField(default=0)),
                ('generation_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='ngenerate_sessions.session')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GenerationProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('generation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='ngenerate_sessions.generationrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='generationrun',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_generation_run_version_per_session'),
        ),
    ]
