# Generated by Django 5.2.11 on 2026-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngenerate_sessions', '0008_alter_processingstep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='emotion',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('serious', 'Serious')], max_length=50),
        ),
    ]
