# Generated by Django 5.2.11 on 2026-02-22 06:41

import asset.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngenerate_sessions', '0004_remove_character_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=asset.models.character_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='ngenerate_sessions.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_images', to='ngenerate_sessions.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'character'), name='unique_character_image_per_session')],
            },
        ),
        migrations.CreateModel(
            name='CharacterVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to=asset.models.character_voice_path)),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_asset', to='ngenerate_sessions.sentence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_voices', to='ngenerate_sessions.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='asset_chara_session_1630fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='IllustrationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=asset.models.illustration_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_asset', to='ngenerate_sessions.illustration')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='ngenerate_sessions.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='asset_illus_session_ac6b45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('video_file', models.FileField(upload_to=asset.models.video_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.FloatField(default=0.0)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ngenerate_sessions.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'version'), name='unique_video_version_per_session')],
            },
        ),
    ]
