# Generated by Django 5.2.11 on 2026-03-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('ngenerate_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_assets', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='characterasset',
            name='scene_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ngenerate_sessions.scenecharacter'),
        ),
        migrations.AddField(
            model_name='characterasset',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_assets', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='characterprofileasset',
            name='character_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='ngenerate_sessions.characterprofile'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='illustration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='ngenerate_sessions.illustration'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_assets', to='ngenerate_sessions.sentence'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='video',
            name='generation_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='video',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ngenerate_sessions.session'),
        ),
        migrations.AddConstraint(
            model_name='characterasset',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'scene_character'), name='unique_character_asset_per_run'),
        ),
        migrations.AddConstraint(
            model_name='illustrationimage',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'illustration'), name='unique_illustration_image_per_run'),
        ),
        migrations.AddConstraint(
            model_name='narratorvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'sentence'), name='unique_narrator_voice_per_run'),
        ),
    ]
