# Generated by Django 5.2.11 on 2026-03-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('ngenerate_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='ngenerate_sessions.character'),
        ),
        migrations.AddField(
            model_name='characterasset',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_assets', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='characterprofileasset',
            name='character_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='ngenerate_sessions.characterprofile'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='illustration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_asset', to='ngenerate_sessions.illustration'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_asset', to='ngenerate_sessions.sentence'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='ngenerate_sessions.session'),
        ),
        migrations.AddField(
            model_name='video',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ngenerate_sessions.session'),
        ),
        migrations.AddIndex(
            model_name='characterasset',
            index=models.Index(fields=['session'], name='asset_chara_session_4f6595_idx'),
        ),
        migrations.AddIndex(
            model_name='illustrationimage',
            index=models.Index(fields=['session'], name='asset_illus_session_ac6b45_idx'),
        ),
        migrations.AddIndex(
            model_name='narratorvoice',
            index=models.Index(fields=['session'], name='asset_narra_session_cd1035_idx'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_video_version_per_session'),
        ),
    ]
