# Generated by Django 5.2.11 on 2026-03-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
        ('ngenerate_sessions', '0008_alter_processingstep_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='video',
            name='unique_video_version_per_session',
        ),
        migrations.RemoveIndex(
            model_name='characterasset',
            name='asset_chara_session_4f6595_idx',
        ),
        migrations.RemoveIndex(
            model_name='illustrationimage',
            name='asset_illus_session_ac6b45_idx',
        ),
        migrations.RemoveIndex(
            model_name='narratorvoice',
            name='asset_narra_session_cd1035_idx',
        ),
        migrations.RemoveField(
            model_name='video',
            name='version',
        ),
        migrations.AddField(
            model_name='characterasset',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_assets', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='illustrationimage',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='narratorvoice',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AddField(
            model_name='video',
            name='generation_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='ngenerate_sessions.generationrun'),
        ),
        migrations.AlterField(
            model_name='characterasset',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ngenerate_sessions.character'),
        ),
        migrations.AlterField(
            model_name='illustrationimage',
            name='illustration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='ngenerate_sessions.illustration'),
        ),
        migrations.AlterField(
            model_name='narratorvoice',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_assets', to='ngenerate_sessions.sentence'),
        ),
        migrations.AddConstraint(
            model_name='characterasset',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'character'), name='unique_character_asset_per_run'),
        ),
        migrations.AddConstraint(
            model_name='illustrationimage',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'illustration'), name='unique_illustration_image_per_run'),
        ),
        migrations.AddConstraint(
            model_name='narratorvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_run__isnull', False)), fields=('generation_run', 'sentence'), name='unique_narrator_voice_per_run'),
        ),
    ]
