# Generated by Django 5.2.11 on 2026-02-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredit',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='usercredit',
            name='used',
        ),
    ]
