# Generated by Django 5.2.11 on 2026-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('google_login', 'Google Login 2FA')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose'], name='users_otpco_email_2071a4_idx')],
            },
        ),
    ]
