# Generated by Django 5.2.11 on 2026-02-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='activate', max_length=10),
        ),
    ]
