# Generated by Django 5.2.11 on 2026-03-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('google_login', 'Google Login 2FA'), ('register', 'Register Verification')], max_length=20),
        ),
    ]
