# Generated by Django 5.2.11 on 2026-02-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('deleted', 'Deleted'), ('suspended', 'Suspended')], default='activate', max_length=10),
        ),
    ]
